//---------------Answers------------------
GET http://localhost:9997/api/answers

###

POST http://localhost:9997/api/answers
Content-Type: application/json

{
  "question": "reefeggdsf",
  "answer": "gsgsfgsdfgs",
  "id_category": 1
}

###

POST http://localhost:9997/api/answers/up
Content-Type: application/json

{
  "id": 7,
  "question": "hh",
  "answer": "rr"

}

###

DELETE http://localhost:9997/api/answers/5

###



//---------------Search------------
GET http://localhost:9997/api/answers/search?q=ree

###




//------------Categories----------------
GET http://localhost:9997/api/categories

###


POST http://localhost:9997/api/categories
Content-Type: application/json

{
  "name": "Салом"
}

###

DELETE http://localhost:9997/api/categories/1

###

POST http://localhost:9997/api/categories/up
Content-Type: application/json

{
  "id": 1,
  "name": "Салом"
}

###